# practice melt pivot_table

In [21]:
import pandas as pd
import numpy as np

# Sample 1: Student test scores (wide format - good for melting)
students_wide = pd.DataFrame({
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'math_score': [85, 92, 78, 95, 88],
    'english_score': [90, 85, 88, 92, 95],
    'science_score': [88, 90, 85, 89, 92],
    'history_score': [92, 88, 90, 94, 87]
})

print("Original Wide Format:")
print(students_wide)

Original Wide Format:
   student_id     name  math_score  english_score  science_score  \
0         101    Alice          85             90             88
1         102      Bob          92             85             90
2         103  Charlie          78             88             85
3         104    Diana          95             92             89
4         105      Eve          88             95             92

   history_score
0             92
1             88
2             90
3             94
4             87

In [22]:
df1=students_wide.melt(id_vars='student_id',
                   value_vars=['math_score', 'english_score', 'science_score', 'history_score'],
                   var_name='subject',
                   value_name='score')
print(df1)

    student_id        subject  score
0          101     math_score     85
1          102     math_score     92
2          103     math_score     78
3          104     math_score     95
4          105     math_score     88
5          101  english_score     90
6          102  english_score     85
7          103  english_score     88
8          104  english_score     92
9          105  english_score     95
10         101  science_score     88
11         102  science_score     90
12         103  science_score     85
13         104  science_score     89
14         105  science_score     92
15         101  history_score     92
16         102  history_score     88
17         103  history_score     90
18         104  history_score     94
19         105  history_score     87

In [23]:
df1.pivot_table(values='score', index='student_id', columns='subject', )

subject     english_score  history_score  math_score  science_score
student_id
101                  90.0           92.0        85.0           88.0
102                  85.0           88.0        92.0           90.0
103                  88.0           90.0        78.0           85.0
104                  92.0           94.0        95.0           89.0
105                  95.0           87.0        88.0           92.0

In [24]:
# Sample 2: Sales data across quarters
sales_wide = pd.DataFrame({
    'product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories'],
    'Q1_2024': [100, 250, 150, 80, 300],
    'Q2_2024': [120, 280, 140, 90, 320],
    'Q3_2024': [110, 300, 160, 85, 310],
    'Q4_2024': [130, 320, 170, 95, 330]
})

print("\nSales Data (Wide Format):")
print(sales_wide)

df1=sales_wide.melt(id_vars=['product', 'category'],
            value_vars=['Q1_2024', 'Q2_2024','Q3_2024','Q4_2024'],
            var_name='season',
                value_name='quantity')

print(df1.pivot_table(values='quantity',index=['product', 'category'], columns='season')
)

Sales Data (Wide Format):
    product     category  Q1_2024  Q2_2024  Q3_2024  Q4_2024
0    Laptop  Electronics      100      120      110      130
1     Phone  Electronics      250      280      300      320
2    Tablet  Electronics      150      140      160      170
3   Monitor  Electronics       80       90       85       95
4  Keyboard  Accessories      300      320      310      330
season                Q1_2024  Q2_2024  Q3_2024  Q4_2024
product  category
Keyboard Accessories    300.0    320.0    310.0    330.0
Laptop   Electronics    100.0    120.0    110.0    130.0
Monitor  Electronics     80.0     90.0     85.0     95.0
Phone    Electronics    250.0    280.0    300.0    320.0
Tablet   Electronics    150.0    140.0    160.0    170.0

In [25]:
# Sample 3: Temperature data across cities
weather_wide = pd.DataFrame({
    'date': pd.date_range('2024-01-01', periods=7, freq='D'),
    'New_York': [32, 35, 30, 28, 33, 36, 34],
    'Los_Angeles': [65, 68, 70, 67, 69, 71, 68],
    'Chicago': [25, 28, 22, 20, 27, 30, 26],
    'Miami': [75, 78, 80, 77, 79, 82, 76]
})

weather_wide.melt(id_vars='date', 
                  value_vars=['New_York', 'Los_Angeles', 'Chicago', 'Miami'],
                  value_name='value',
                  var_name='city'
                  )\
    .pivot_table(values='value',index='date', columns='city')

city        Chicago  Los_Angeles  Miami  New_York
date
2024-01-01     25.0         65.0   75.0      32.0
2024-01-02     28.0         68.0   78.0      35.0
2024-01-03     22.0         70.0   80.0      30.0
2024-01-04     20.0         67.0   77.0      28.0
2024-01-05     27.0         69.0   79.0      33.0
2024-01-06     30.0         71.0   82.0      36.0
2024-01-07     26.0         68.0   76.0      34.0

# practice rolling windows and cleaning

In [26]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Create base stock data
stock_data = pd.DataFrame({
    'date': pd.date_range('2024-01-01', periods=10, freq='D'),
    'open': np.random.randint(90, 110, 10),
    'close': np.random.randint(90, 110, 10),
    'volume': np.random.randint(1000, 5000, 10)
})

# 1. Introduce missing values (NaN)
stock_data.loc[2, 'open'] = np.nan
stock_data.loc[5, 'close'] = np.nan
stock_data.loc[7, 'volume'] = np.nan
stock_data.loc[8, ['open', 'close']] = np.nan

# 2. Add duplicate rows
duplicate_row = stock_data.iloc[3].copy()
stock_data = pd.concat([stock_data, pd.DataFrame([duplicate_row])], ignore_index=True)
duplicate_row2 = stock_data.iloc[6].copy()
stock_data = pd.concat([stock_data, pd.DataFrame([duplicate_row2])], ignore_index=True)

# 3. Add extreme outlier values
stock_data.loc[1, 'volume'] = 50000  # Extremely high volume
stock_data.loc[4, 'open'] = 5        # Unrealistically low price
stock_data.loc[9, 'close'] = 500     # Extremely high price

# 4. Add some additional data quality issues
stock_data.loc[len(stock_data)] = [pd.Timestamp('2024-01-05'), 95, 98, -100]  # Negative volume
stock_data.loc[len(stock_data)] = [pd.NaT, 100, 105, 2000]  # Missing date

# Shuffle the data to make it more realistic
stock_data = stock_data.sample(frac=1).reset_index(drop=True)

C:\Users\xiang\AppData\Local\Temp\ipykernel_29356\2884312405.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stock_data.loc[len(stock_data)] = [pd.NaT, 100, 105, 2000]  # Missing date

In [27]:
# unique values
stock_data.drop_duplicates(subset=['date'],inplace=True)
print(stock_data['date'].nunique())
print(len(stock_data['date']))
print(stock_data['date'].isna().sum())

10
11
1

In [28]:
stock_data['date'].astype(str).replace('NaT', np.nan).fillna('missing value')
stock_data['date'].astype(str).replace('NaT', np.nan).dropna()

0     2024-01-10
1     2024-01-02
2     2024-01-06
3     2024-01-01
4     2024-01-04
5     2024-01-08
6     2024-01-05
8     2024-01-09
10    2024-01-07
12    2024-01-03
Name: date, dtype: object

In [29]:
stock_data2=stock_data[(~stock_data['date'].isna()) 
                       & (~stock_data['open'].isna())
                       & (~stock_data['close'].isna()) ]
stock_data2.info()
stock_data2.head()
stock_data2=stock_data2.sort_values(by='date').reset_index(drop=True)

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    7 non-null      datetime64[ns]
 1   open    7 non-null      float64
 2   close   7 non-null      float64
 3   volume  6 non-null      float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 280.0 bytes

In [30]:
median_open=stock_data2['open'].median()
median_close=stock_data2['close'].median()

open_low=stock_data2['open'].min()
open_high=stock_data2['open'].quantile(0.9)

close_low=stock_data2['close'].quantile(0.1)
close_high=stock_data2['close'].quantile(0.9)
# clean data to replace extreme value with median
condition_list=[stock_data2['open']<=open_low, 
                stock_data2['open']>open_high]
choice_list=[median_open,median_open]

condition_list2=[stock_data2['close']<close_low, 
                stock_data2['close']>close_high]
choice_list2=[median_close,median_close]

stock_data2['open2']=np.select(condition_list, choice_list,default=stock_data2['open'])
stock_data2['close2']=np.select(condition_list2, choice_list2,default=stock_data2['close'])

stock_data2.loc[:,'open2':'close2'].describe()

            open2      close2
count    7.000000    7.000000
mean    99.571429   97.142857
std      4.613644    3.184785
min     93.000000   92.000000
25%     98.000000   96.000000
50%    100.000000   97.000000
75%    100.000000   99.000000
max    108.000000  101.000000

In [31]:

# Daily returns
stock_data2['daily_return'] =(stock_data2['close2']-stock_data2['open2'])/stock_data2['open2']

# Intraday change
stock_data2['intraday_change'] = stock_data2['open2'].diff(1)

# 5-day moving average
stock_data2['momentum_5d'] =stock_data2['open2'].rolling(5).mean()

stock_data2

,date,open,close,volume,open2,close2,daily_return,intraday_change,momentum_5d
0,2024-01-01,96.0,97.0,1474.0,96.0,97.0,0.010417,NaN,NaN
1,2024-01-02,109.0,92.0,50000.0,100.0,92.0,-0.080000,4.0,NaN
2,2024-01-04,100.0,101.0,4753.0,100.0,101.0,0.010000,0.0,NaN
3,2024-01-05,5.0,95.0,3047.0,100.0,95.0,-0.050000,0.0,NaN
4,2024-01-07,108.0,90.0,3747.0,108.0,97.0,-0.101852,8.0,100.8
5,2024-01-08,100.0,101.0,NaN,100.0,101.0,0.010000,-8.0,101.6
6,2024-01-10,93.0,500.0,1189.0,93.0,97.0,0.043011,-7.0,100.2