
## <center> Intro to Dataframes

In [1]:
import pandas as pd

In [2]:
scores = {"name":['Ray','Japhy','Zosa'],
          "city":['San Francisco','San Francisco','Denver'],
          "score":[75,92]
         }

In [16]:
try:
    df = pd.DataFrame(scores)
except Exception as e:
    print("Error: array must the same length")
    scores['score'].append(30)
    df = pd.DataFrame(scores)

Error: array must the same length

note: converting to df from a arrays of same length

In [17]:
df

    name           city  score
0    Ray  San Francisco     75
1  Japhy  San Francisco     92
2   Zosa         Denver     30

In [18]:
# access columns
df['score']

0    75
1    92
2    30
Name: score, dtype: int64

In [ ]:
# create a new column
df['name_city'] = df['name'] + '_' + df['city']

In [19]:
# return rows when a condition is met
df[df['score']>90]

    name           city  score
1  Japhy  San Francisco     92

In [21]:
df[df['score']>90]['score']

1    92
Name: score, dtype: int64