## <center> Beyond Pandas with Dask and Spark

## What is Dask?

### Introducing the Dask DataFrame

In [11]:
import dask.dataframe as dd
df = dd.read_csv('iris.csv')

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## What is Apache Spark?

### Introducing Koalas

In [12]:
import pandas as pd
import numpy as np
import databricks.koalas as ks
from pyspark.sql import SparkSession

In [13]:
pdf = pd.DataFrame(np.random.randn(6, 4),  columns=list('ABCD'))
pdf.head()

          A         B         C         D
0 -0.825701 -0.574163  0.671572 -0.061950
1  2.154309 -0.710903  0.333723  0.709683
2  0.199930 -0.578183 -0.204948  0.025136
3 -1.334694  1.586253  0.788930  0.578177
4  1.555822  0.135067  0.347151  0.056300

In [14]:
kdf = ks.from_pandas(pdf)
kdf.head()

          A         B         C         D
0 -0.825701 -0.574163  0.671572 -0.061950
1  2.154309 -0.710903  0.333723  0.709683
2  0.199930 -0.578183 -0.204948  0.025136
3 -1.334694  1.586253  0.788930  0.578177
4  1.555822  0.135067  0.347151  0.056300

check out databrick, koalas, dask